name: ci-matrix

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

jobs:
  build:
    name: Build node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Cache sccache results
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.cargo/cache
          key: ${{ runner.os }}-0001
      - name: Build ${{ matrix.os }}
        run: |
          rustup show
          rustup update stable
          rustup show
          rustup component add rustfmt
          rustup component add clippy
          ./ci/all.sh
          ./ci/multinode_integration_test.sh
          ./ci/collect_results.sh
        shell: bash
      - name: Publish ${{ matrix.os }}
        uses: actions/upload-artifact@v1
        with:
          name: Build Results ${{ matrix.os }}
          path: results
  glue:
    name: Glue Artficats for ${{ matrix.os }}
    needs: Build node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Download artifact for  ${{ matrix.os }}
        uses: actions/download-artifact@v2
        with:
          name: Build Results ${{ matrix.os }}
          path: results
      - shell: bash
        run: |
          tar cvfz results >> results.tgz
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v2
        with:
          name: Build Results ${{ matrix.os }}
          path: results.tgz