name: s3

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

jobs:
  build:
    name: Build node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Cache sccache results
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.cargo/cache
          key: ${{ runner.os }}-0001
      - name: Build ${{ matrix.os }}
        run: |
          rustup show
          rustup update stable
          rustup show
          rustup component add rustfmt
          rustup component add clippy
          ./ci/all.sh
          ./ci/multinode_integration_test.sh
          ./ci/collect_results.sh
        shell: bash
      - name: Publish ${{ matrix.os }}
        uses: actions/upload-artifact@v1
        with:
          name: Build Results ${{ matrix.os }}
          path: results
  upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    needs: build
    steps:
      - name: Download artifact for  ${{ matrix.os }}
        uses: actions/download-artifact@v2
        with:
          name: Build Results ${{ matrix.os }}
          path: results
      - name: Upload  ${{ matrix.os }} to s3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: './'
          destination_dir: ${{ matrix.os }}

      
